# Formação Cientista de Dados
Prof. Fernando Amaral

numpy

In [1]:
# Este código importa a biblioteca NumPy e a renomeia como "np".

import numpy as np

In [2]:
# Cria uma matriz unidimensional (mt)
# O código cria uma matriz de números e a exibe, mostrando o tipo de dado utilizado.

mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [3]:
# Criar o array com um tipo específico.
# Este código cria dois arrays numéricos usando a biblioteca NumPy: um array de números reais 
# (floats de 64 bits) e um array de números inteiros (inteiros de 32 bits), demonstrando o uso 
# de tipos de dados específicos em arrays.

mtfloat = np.array([1, 2, 3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1, 2, 3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [10]:
# Mudar o tipo do array.
# Este código cria um array de números reais, mostra os números originais e, 
# em seguida, converte esses números em números inteiros, exibindo a versão 
# truncada dos números inteiros resultantes.

mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])
print(mtnew)

# quando transformamos de float para int os valores são truncados.

mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4       3.6      -5.1       9.42      4.999999]
[ 1  3 -5  9  4]


In [5]:
# Podemos fazer o inverso também.
# Este código cria uma matriz de números inteiros de 1 a 4, mostra essa matriz e, 
# em seguida, converte essa matriz para números de ponto flutuante e a mostra novamente.

mt5 = np.array([1, 2, 3, 4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [6]:
# Mais de uma dimensão
# O código cria uma matriz de duas dimensões (3x3) usando a biblioteca NumPy e imprime a matriz.

mt7 = np.array([[7,2,23],[12,27,4],[5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [11]:
# Criar arrays vazios tipificados.
# Empty significa que não são inicializados, não que são vazios.
# Este código utiliza a biblioteca NumPy para criar e imprimir diferentes tipos de matrizes: 
# um array vazio de números inteiros, uma matriz de zeros, uma matriz de uns e uma matriz 
# diagonal com uns na diagonal principal e zeros nas outras posições.

vazio = np.empty([3,2], dtype = int)
print(vazio)
print("-------")

# cria uma matriz 4x3 com valores zero.

zeros = np.zeros([4,3])
print(zeros)
print("-------")

# com valores igual a um.

um = np.ones([5,7])
print(um)
print("-------")

# cria matriz quadrada com diagonal principal com valores 1 e os outros valores zero.

diagonal = np.eye(5)
print(diagonal)


[[ 1193320256         595]
 [          0           0]
 [     131074 -2147483648]]
-------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
-------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
# Este código gera e exibe diferentes conjuntos de números aleatórios: 
# - O primeiro contém valores entre zero e um.
# - O segundo contém valores aleatórios seguindo uma distribuição normal (que pode incluir números negativos).
#-  O terceiro é uma matriz 3x4 de valores aleatórios multiplicados por 10.
# - O quarto é um conjunto de 10 valores aleatórios seguindo uma distribuição normal multiplicados por 10.

# Valores aleatórios entre zero e um.
ale = np.random.random((5))
print(ale)
print("-------")

# Valores aleatórios distr. normal contendo negativos.
ale2= np.random.randn((5))
print(ale2)
print("-------")

# Valores aleatórios 3 x 4.
ale3 = (10*np.random.random((3,4)))
print(ale3)
print("-------")

# Valores aleatórios 3 x 4.
ale4 = (10*np.random.randn((10)))
print(ale4)

[0.27855999 0.04362713 0.7398121  0.4075575  0.78012055]
-------
[-0.39532205  0.43076078 -0.21325318 -0.09915622 -0.25962057]
-------
[[2.77806413 6.0971635  5.58049    3.01495045]
 [8.55169549 9.1307168  2.47005877 5.41416424]
 [2.95372996 5.97114243 1.85456088 4.62827322]]
-------
[  0.49368893  -9.83978585   7.93369054 -16.40972013  -4.33359426
  11.30881126  -5.88750584  11.35642795  -6.35827058  21.75426067]


In [13]:
# Este código utiliza a biblioteca NumPy para gerar números aleatórios, permitindo controlar 
# a aleatoriedade usando uma semente específica e criando tanto números decimais quanto inteiros aleatórios.

# Gera números decimais
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print (ale5)

# Gera números inteiros
ale6 = gnr.integers(10, size=(3, 4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [6]:
# unique remove repetições.
# Este código utiliza a biblioteca NumPy para remover os elementos repetidos do array 'j' 
# e depois imprime o array sem repetições.

j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
print(j)
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 12 13 11 18 19 20]
[11 12 13 14 15 16 17 18 19 20]


In [14]:
# Este código cria uma matriz 3x3 chamada "k", mostra essa matriz, 
# exibe um elemento específico dela e imprime as dimensões da matriz.

k = np.array([[17,22,43],[27,25,14],[15,24,32]])
print(k)
print(k[0][1])
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


In [15]:
# Funções Matemáticas - Esse código calcula e imprime o valor máximo, mínimo, soma, média e 
#desvio padrão dos valores em uma matriz chamada 'k'.

# Mostra o maior valor da matriz k
print(k.max())

# Mostra o menor valor da matriz k
print(k.min())

# Mostra a soma dos valores da matriz k
print((k.sum()))

# Mostra o valor da média dos valores da matriz k
print(k.mean())

# Mostra o valor do desvio padrão (standard deviation) dos valores da matiz k
print(k.std())

43
14
219
24.333333333333332
8.615231988880057


In [16]:
# Funções universais, aplicadas a todos os elementos - Este código utiliza a biblioteca numpy para 
# calcular e mostrar a raiz quadrada e o valor exponencial de cada elemento presente no array 'k1'.

# Mostra o valor da raiz quadrada de todos elementos
k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))
print()

# Mostra o valor do exponencial de todos elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]

[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [17]:
# Extração de elementos - Esse código cria um array de números de 1 a 13 e depois imprime 
# diferentes partes desse array, incluindo um elemento específico, um subarray dos primeiros 
# dois elementos, um subarray a partir da segunda posição até o final e um subarray dos três últimos elementos.

m = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])

# Mostra o elemento da posição 2.
print(m[1])
print("-------")

# Mostra o array criado a partir da posição 0, dois elementos.
print(m[0:2])
print("-------")

# Mostra o array criado a partir da 2a posição até todo o restante do array.
print(m[1:])
print("-------")

# Mostra o array criado a partir da antepenúltima posição até o final.
print(m[-3:])

2
-------
[1 2]
-------
[ 2  3  4  5  6  7  8  9 10 11 12 13]
-------
[11 12 13]


In [18]:
# Este código utiliza a biblioteca NumPy para criar uma matriz de números, em seguida, 
# extrai e imprime diferentes partes dessa matriz, incluindo a primeira linha, todas as 
# linhas, primeira coluna e segunda coluna.

# Extração de linhas e colunas.
l = np.array([[4, 5], [6, 1], [7, 4]])
print(l)
print("-----------")

# Primeira linha, todas as colunas.
l_linha_1 = l[0, :]
print(l_linha_1)
print("-----------")

# Segunda linha.
l_linha_2 = l[1, :]
print(l_linha_2)
print("-----------")

# Terceira linha.
l_linha_3 = l[2, :]
print(l_linha_3)
print("-----------")

# Todas as linhas, primeira coluna.
l_coluna_1 = l[:, 0]
print(l_coluna_1)
print("-----------")

# Todas as linhas, segunda coluna.
l_coluna_2 = l[:, 1]
print(l_coluna_2)

[[4 5]
 [6 1]
 [7 4]]
-----------
[4 5]
-----------
[6 1]
-----------
[7 4]
-----------
[4 6 7]
-----------
[5 1 4]


In [19]:
# Este código realiza operações com matrizes: primeiro, ele adiciona e multiplica duas 
# matrizes "n" e "o", depois imprime os resultados; em seguida, ele adiciona a matriz "q" à 
# matriz "p" e imprime o resultado dessa adição.

# Adição e multiplicação de matrizes.
n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])

# Adição entre duas matrizes.
res1 = n + o
print(res1)
print("-----------")

# Multiplicação entre 2 matrizes.
res2 = n * o
print(res2)
print("-----------")

# Adição entre duas matrizes durante a impressão.
p = np.array([[1, 2], [3, 4], [5, 6]])
q = np.array([[2, 1]])
print(p + q)

[[2 3]
 [4 5]]
-----------
[[1 2]
 [3 4]]
-----------
[[3 3]
 [5 5]
 [7 7]]


In [21]:
# Transposição, rearranja um conjunto de 15 elementos de 0 a 14 .
# O código cria uma matriz 3x5 com números de 0 a 14, mostra a matriz original e, em seguida, 
# mostra a matriz transposta (linhas e colunas trocadas).

# Mostra 3 linhas e 5 colunas.
f = np.arange(15).reshape((3, 5))

# Mostra a matrizes transposta entre linha e coluna
print(f)
print("-----------------")
s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-----------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [23]:
# O código cria uma matriz 3x5 usando numpy, depois mostra a matriz original e sua transposta.

# Outra forma de fazer com o mesmo resultado.
r = np.arange(15).reshape((3, 5))
print(r)
print("---------------------")

# Rearranja um conjunto de 15 elementos e mostra a matrizes transposta entre linha e coluna.
s = r.transpose((1,0))
print(s)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
---------------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [24]:
# Expressões lógicas - Este código cria e manipula matrizes usando expressões lógicas: 
# ele gera uma matriz de números aleatórios, cria uma matriz booleana com base nessa matriz 
# original e, em seguida, cria uma matriz onde os valores positivos da matriz booleana são 
# substituídos por 1 e os valores negativos são substituídos por -1.

# Criando matriz com valores aleatórios positivos e negativos
v = np.random.randn(4, 4)
print(v)
print("------------------------------------------------------")

# Criando matriz com valores booleanos baseado no array v
x = (v > 0)
print(x)
print("------------------------------------------------------")

# Criando matriz com valores -1 e 1 baseado nos valores do array x
z = np.where(x > 0, 1, -1)
print(z)


[[-0.36540208  0.40183553  0.590876    0.35236738]
 [ 0.09628865 -1.15452083 -1.15158663 -2.87953221]
 [-0.79949553  1.2760657  -0.70011352  1.09644254]
 [-0.47181098  1.6143356  -0.63418684 -1.41299392]]
------------------------------------------------------
[[False  True  True  True]
 [ True False False False]
 [False  True False  True]
 [False  True False False]]
------------------------------------------------------
[[-1  1  1  1]
 [ 1 -1 -1 -1]
 [-1  1 -1  1]
 [-1  1 -1 -1]]
